### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kimatelier622** [juniormfreitas/react-typescript-webpack-boilerplate#1]
i get an error :SyntaxError: Cannot use import statement outside a module, 
with write target:es5 and module:esnext .
  how can i solve this problem?   i try change module to "CommonJs"

**Comment by thejfreitas** [comment]
@Ken-Scofield Are you trying to import something from an external lib or a component that you created in your project? Can you give me more details?

**Comment by kimatelier622** [comment]
import { Configuration, HotModuleReplacementPlugin } from 'webpack';
import { merge } from 'webpack-merge';   // 
import commonConfig from './webpack.config.common'
import 'webpack-dev-server'

const config: Configuration = {
  mode: 'development',
  devtool: 'cheap-module-source-map',
  devServer: {
    hot: false
  }
}

export default merge(commonConfig, config)
nothing ,just like this

**Comment by kimatelier622** [comment]
import { merge } line2 occurs this error

**Comment by kimatelier622** [comment]
error about node version?  module:"commonjs" can solve this, i just want know y

**Comment by thejfreitas** [comment]
@Ken-Scofield I'm not getting this error on my end. I'm running on node v14.15.0. Either way I just updated the `webpack.dev.ts` also updated some types. Can you pull the code on main branch try again and let me know how it goes?

**Comment by kimatelier622** [comment]
thank you, i didn't pull code before. I'll try

**Comment by kimatelier622** [comment]
i find branch main file  'tsconfig.js' was written as 'tscofig.js', compiler cant resolve ,so u don't occurs this error

**Comment by thejfreitas** [comment]
If you rename your tsconfig file to .json extension you will be fine

**Comment by kimatelier622** [comment]
i was wrong,  that's tsconfig.json , was occurs this error ,not tsconfig.js
